USE KHOHANG
GO

--HOLDLOCK Ở ĐÂY ĐÓNG VAI TRÒ NHƯ RLOCK => CHẶN UPDATE, CHỈ CHO ĐỌC Ở CÁC TRANSACTION KHÁC
BEGIN TRAN
SELECT * FROM SANPHAM WITH(HOLDLOCK) WHERE MASP = 'SP01'
WAITFOR DELAY '00:00:5'
SELECT * FROM SANPHAM WHERE MASP = 'SP01'
COMMIT TRAN
