USE KHOHANG
GO
--UPDATE SANPHAM SET TONKHO = 50 WHERE MASP = 'SP01'
BEGIN TRY
BEGIN TRAN
UPDATE SANPHAM SET TONKHO -= 5 WHERE MASP = 'SP01'
WAITFOR DELAY '00:00:05'
UPDATE SANPHAM SET TONKHO = 100 WHERE MASP = 1
COMMIT TRAN 
PRINT 'COMMITTED'
END TRY
BEGIN CATCH
PRINT 'NOT COMMITTED'
ROLLBACK TRAN
END CATCH
SELECT * from SANPHAM WHERE MASP ='SP01'