USE KHOHANG
GO
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM SANPHAM  WHERE MASP = 'SP01'
WAITFOR DELAY '00:00:05'
SELECT * FROM SANPHAM WHERE MASP = 'SP01'
COMMIT TRAN
SELECT * FROM SANPHAM WHERE MASP = 'SP01'
