-- Giả sử cơ chế isolation level ở mức thấp nhất và dùng lock để giải quyết
USE KHOHANG
GO
SEt TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM SANPHAM WITH (READCOMMITTEDLOCK)  WHERE MASP = 'SP01'
COMMIT TRAN

