USE KHOHANG
GO
Exec cap_nhat_ton_kho @v_masp = 'SP01', @v_tonkho = 5
select * from SANPHAM where masp = 'SP01'

-- USE KHOHANG
-- GO

-- BEGIN TRY
-- BEGIN TRAN
-- DECLARE @TONKHO INT = (SELECT TONKHO FROM WITH (UPDLOCK) SANPHAM WHERE MASP = 'SP01')
-- PRINT N'TON KHO: ' + CAST(@TONKHO AS NVARCHAR)
-- WAITFOR DELAY '00:00:05'
-- SET @TONKHO -= 5
-- UPDATE SANPHAM SET TONKHO = @TONKHO WHERE MASP = 'SP01'
-- COMMIT TRAN
-- END TRY

-- BEGIN CATCH
-- PRINT 'NOT COMMITTED'
-- END CATCH
-- SELECT TONKHO FROM SANPHAM WHERE MASP = 'SP01'