USE KHOHANG
GO
-- 1 TRONG 2 TRANSACTION SẼ BỊ BỊ LỖI VÀ ROLLBACK
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRY
BEGIN TRAN
DECLARE @TONKHO INT = (SELECT TONKHO FROM SANPHAM WHERE MASP = 'SP01')
PRINT N'TON KHO: ' + CAST(@TONKHO AS NVARCHAR)

SET @TONKHO -= 5
UPDATE SANPHAM SET TONKHO = @TONKHO WHERE MASP = 'SP01'
COMMIT TRAN
END TRY

BEGIN CATCH
PRINT 'NOT COMMITTED'
END CATCH
SELECT TONKHO FROM SANPHAM WHERE MASP = 'SP01'