USE KHOHANG
GO
--UPDATE SANPHAM SET TONKHO = 40 WHERE MASP = 'SP01'
BEGIN TRY
BEGIN TRAN
DECLARE @TONKHO INT = (SELECT TONKHO FROM SANPHAM WHERE MASP = 'SP01')
PRINT N'TON KHO: ' + CAST(@TONKHO AS NVARCHAR)

SET @TONKHO -= 10
UPDATE SANPHAM SET TONKHO = @TONKHO WHERE MASP = 'SP01'
COMMIT TRAN
END TRY

BEGIN CATCH
PRINT 'NOT COMMITTED'
END CATCH
SELECT TONKHO FROM SANPHAM WHERE MASP = 'SP01'