USE KHOHANG
GO

BEGIN TRY
BEGIN TRAN
DECLARE @TONKHO INT = (SELECT TONKHO FROM  SANPHAM WHERE MASP = 'SP01')
PRINT N'TON KHO: ' + CAST(@TONKHO AS NVARCHAR)
SET @TONKHO -= 6
IF @TONKHO < 0 
        THROW 50001, N'Số lượng tồn kho không đủ', 1;

UPDATE SANPHAM SET TONKHO = @TONKHO WHERE MASP = 'SP01'
COMMIT TRAN
END TRY

BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK
    PRINT ERROR_MESSAGE()
END CATCH
SELECT * FROM SANPHAM WHERE MASP = 'SP01'

-- UPDATE SANPHAM SET TONKHO = 10 WHERE MASP = 'SP01'