USE KHOHANG
GO

BEGIN TRAN
SELECT * FROM SANPHAM WITH(HOLDLOCK) WHERE MASP = 'SP01'
WAITFOR DELAY '00:00:05'
SELECT * FROM SANPHAM WHERE MASP = 'SP01'
COMMIT TRAN
SELECT * FROM SANPHAM WHERE MASP = 'SP01'