USE KHOHANG
GO
--UPDATE SANPHAM SET TONKHO = 50 WHERE MASP = 'SP01' 
select * from sanpham
BEGIN TRAN
SELECT sum(tonkho) FROM SANPHAM  with(HOLDLOCK)
WAITFOR DELAY '00:00:05'
SELECT sum(tonkho) FROM SANPHAM 
COMMIT TRAN
select * from sanpham
