USE KHOHANG
GO

BEGIN TRY
BEGIN TRAN
UPDATE SANPHAM SET TONKHO = 50 WHERE MASP = 'SP01'
UPDATE SANPHAM SET TONKHO = 100 WHERE MASP = 1
COMMIT TRAN
PRINT 'COMMITTED'
END TRY

BEGIN CATCH
PRINT 'NOT COMMITTED'
WAITFOR DELAY '00:00:05'
ROLLBACK TRAN
END CATCH