USE KHOHANG
GO
BEGIN TRY
    BEGIN TRAN
    UPDATE SANPHAM SET TONKHO = 50 WHERE MASP = 'SP01'
    WAITFOR DELAY '00:00:10' 
    UPDATE SANPHAM SET TONKHO = 100 WHERE MASP = 1 -- lỗi --> rollback
    COMMIT TRAN
    PRINT 'COMMITTED'
END TRY
BEGIN CATCH
    PRINT N'NOT COMMITTED. ROLL BACK'
    ROLLBACK TRAN
END CATCH