USE KHOHANG
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM SANPHAM
WAITFOR DELAY '00:00:10'
SELECT * FROM SANPHAM
COMMIT TRAN
-- Kiểm tra, không thêm delay thì vẫn không được sản phẩm được thêm vào
WAITFOR DELAY '00:00:01'
SELECT * FROM SANPHAM
