-- RULE: NHANVIEN before SANPHAM
USE KHOHANG
GO

BEGIN TRAN
UPDATE NHANVIEN SET CHUCVU = 'ABC' WHERE HOTEN = N'Nguyễn Văn An'

WAITFOR DELAY '00:00:05' 

UPDATE SANPHAM SET TONKHO = 1 WHERE MASP = 'SP01'

COMMIT TRAN