USE KHOHANG
GO

SET DEADLOCK_PRIORITY HIGH

BEGIN TRAN

UPDATE SANPHAM SET TONKHO = TONKHO - 1 WHERE MASP = 'SP01'

WAITFOR DELAY '00:00:05'

UPDATE SANPHAM SET TONKHO = TONKHO - 1 WHERE MASP = 'SP02'

COMMIT TRAN