USE KHOHANG
GO
DECLARE @RETRY INT = 0
WHILE @RETRY < 3
BEGIN
	BEGIN TRY
		BEGIN TRAN
			UPDATE NHANVIEN SET CHUCVU = 'ABC' WHERE HOTEN = N'Nguyễn Văn An'

			UPDATE SANPHAM SET TONKHO = 1 WHERE MASP = 'SP01'
		COMMIT TRAN
		BREAK
	END TRY
	
	BEGIN CATCH 
		IF ERROR_NUMBER() = 1205
		BEGIN
			PRINT N'DEADLOCK => ROLLBACK'
			ROLLBACK TRAN
			SET @RETRY += 1
			WAITFOR DELAY '00:00:04'
		END
		ELSE
		BEGIN
			ROLLBACK TRAN
			THROW
		END
	END CATCH
END
PRINT N'THUC HIEN THANH CONG'
