USE KHOHANG
GO

SET DEADLOCK_PRIORITY LOW

BEGIN TRAN

UPDATE SANPHAM SET TONKHO = TONKHO - 5 WHERE MASP = 'SP02'
   
WAITFOR DELAY '00:00:05'

UPDATE SANPHAM SET TONKHO = TONKHO - 5 WHERE MASP = 'SP01'

COMMIT TRAN